doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        types:
            experience_id: App\Experiences\Infrastructure\Persistence\Doctrine\Type\ExperienceIdType
            session_id: App\Experiences\Infrastructure\Persistence\Doctrine\Type\SessionIdType
            provider_id: App\Experiences\Infrastructure\Persistence\Doctrine\Type\ProviderIdType
            booking_id: App\Bookings\Infrastructure\Persistence\Doctrine\Type\BookingIdType
            user_id: App\Bookings\Infrastructure\Persistence\Doctrine\Type\UserIdType
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            Shared:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/Mapping/Entity'
                prefix: 'App\Shared\Domain\Entity'
                alias: Shared
            SharedValueObject:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/Mapping/ValueObject'
                prefix: 'App\Shared\Domain\ValueObject'
                alias: SharedValueObject
            Experiences:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Experiences/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Experiences\Domain'
                alias: Experiences
            Bookings:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Bookings/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Bookings\Domain'
                alias: Bookings

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
