doctrine_migrations:
    migrations_paths:
        'App\Experiences\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Experiences/Infrastructure/Persistence/Doctrine/Migrations'
        'App\Bookings\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Bookings/Infrastructure/Persistence/Doctrine/Migrations'
    enable_profiler: false
