# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

experiences_controllers:
    resource:
        path: ../src/Experiences/Infrastructure/Ui/Http/Controller/
        namespace: App\Experiences\Infrastructure\Ui\Http\Controller
    type: attribute

bookings_controllers:
    resource:
        path: ../src/Bookings/Infrastructure/Ui/Http/Controller/
        namespace: App\Bookings\Infrastructure\Ui\Http\Controller
    type: attribute
